spring:
  application: 
    name: inventory-management
  jackson: 
    property-naming-strategy : LOWER_CAMEL_CASE
    serialization:
      fail-on-empty-beans: false
  h2:
    console.enabled: true
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password:
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    defer-datasource-initialization: true
    show-sql: true
  data:
    mongodb:
      #authentication-database: ${MONGO_AUTH:''}
      #username: ${MONGO_USER:''}
      #password: ${MONGO_PWD:''}
      database: ${MONGO_DB:mongoDB}
      port: ${MONGO_PORT:27017}
      host: ${MONGO_HOST:localhost}
  kafka:    producer:      bootstrap-servers:      - localhost:29092,localhost:39092
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
  thymeleaf:
    cache: false
  
server:
    port: ${API_PORT:9091}
app:
  msg-broker-url: ${MSG_BROKER_URL:http://localhost:9092/api/kafka/broker/publish/}
okta:
  oauth2:
    issuer: ${OKTA_ISSUER:''}
    client-id: ${OKTA_CLIENT_ID:''}
    client-secret: ${OKTA_CLIENT_SECRET:''}
logging:
  level: 
    com.inventory.management: DEBUG